### ISSUE TITLE
Minor review and refactor of vaults domain for 'polykey'

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-polykey#718]
### Specification

As part of refactoring the `git` domain in #298 we need to do a small review of the vaults domain for any fixes and improvements. This is a general refactor and review. We're looking for any places that can be tidied up if needed. Some tests need to be re-enabled as well.

### Additional context

* Related: #298
* Related #709
* Related #717
* Related #714
* Related #523

### Tasks

1. General review of the vaults domain.
2. Have a closer look at the vaults committing secrets and git garbage collection code.
3. Determine and apply any optimisations that can be made.
4. Review vaults tests and clean them up if needed.
5. Re-enable any tests that have been disabled.
6. Possibly split up some test files so the vaults domain runs quicker in CI. vault ops is currently very slow.

**Comment by tegefaulkes** [comment]
Yeah, there's definitely some weird interaction with linear going on here.

**Comment by CMCDragonkai** [comment]
You got to be more descriptive with your issue title in the future...
