### ISSUE TITLE
Network Seednodes/Trust Anchor Bootstrapping

### ISSUE THREAD

**Issue by amydevs** [MatrixAI/js-polykey#780]
### Specification

According to https://github.com/MatrixAI/Polykey/issues/779, there needs to be a Trust Anchor that exists to mint `ClaimNetworkAuthority` tokens.

As the Trust Anchor is simply some entity containing state with a public key and private key in order to mint `ClaimNetworkAuthority` tokens, a user can simply store their public/private key in some secrets manager. Since we are building one, one can just use a Polykey Seednode that is designated to being the Trust Authority. Or the Trust Authority could be simply some state stored in a database or on disk.

Anyhow, seednodes are bootstrapped with the authority to delegate `ClaimNetworkAccess` tokens by being given a `ClaimNetworkAuthority` token.

The `ClaimNetworkAuthority` token is generated by the Trust Anchor and passed to each seednode through an environment variable.

### Additional context

https://github.com/MatrixAI/Polykey/issues/779

### Tasks

1. ...
2. ...
3. ...

**Comment by tegefaulkes** [comment]
I'm closing this issue. It will be covered by #781 and #784
