### ISSUE TITLE
Manage multiple transactions dynamically in the vault domain

### ISSUE THREAD

**Issue by aryanjassal** [MatrixAI/js-polykey#821]
### Specification

Currently, we have `VaultInternal.writeF` or `VaultInternal.writeG`, both of which are used to acquire transaction locks, and have a callback function which is executed. After that, the function performs some cleanup and releases the resource. Multiple resources can be requested at the same time, but they need to be known ahead of time.

This is not ideal. If we are streaming in multiple vault-name pairs, then multiple commits will be created for simple operations per vault. For example, if we open a new transaction to create a new file in a vault for each vault, then each file would make a new commit in each vault.

Ideally, all the required files should be created in a single commit per vault. This, however, is not possible as we don't know the vaults at the beginning if the vault-name pairs are being streamed in.

To solve this problem, we can group the inputs by vault names and acquire a single resource per vault, performing all operations in one go. However, this results in the input stream needing to be accumulated in-memory, and the modified in potentially unpredictable way (to the user/caller). This shuffling of inputs could cause issues down the line.

Rather, a new method needs to be added to the vaults domain which allows dynamically creating transactions and closing them all together. This will allow each vault to open a new transaction if it doesn't already exist, or operate on an existing transaction, allowing the input stream to be directly consumed instead of needing to be accumulated or sorted/grouped.

Note that reading from vaults like this isn't an issue, as a commit isn't created for reading, and we can safely spam `vault.readF` or `vault.readG` where needed. (see [**Polykey:src/client/handlers/VaultsSecretsGet:44-68**](https://github.com/MatrixAI/Polykey/blob/ab666368d9f1a46b226813c1c662a601840c2cdb/src/client/handlers/VaultsSecretsGet.ts#L44-L68)). As such, technically the reading version is not required, but can be implemented for completeness.

### Additional context

* Discussion about this problem and it's potential solutions [**Polykey#819 (comment)**](https://github.com/MatrixAI/Polykey/pull/819#issuecomment-2397892930)

### Tasks

1. Create dynamic `vault.write` method
2. Close all transactions elegantly on error or otherwise
3. Make sure RPC handlers like `VaultsSecretsRm` and `VaultsSecretsTouch` can utilise them

**Comment by aryanjassal** [comment]
Brian and I had a discussion about the exact requirements for this issue.

Instead of the original design idea of creating a function like `vault.acquireRead` or `vault.acquireWrite`, we will be simply replicating the pattern from `vaultManager.withVaults`. Multiple `vaultId`s can be specified, and a resource will be acquired for each within that `with` context.

```typescript
const vaultIds = ['id1', 'id2', 'id3'];
const res = vaultManager.writeF(vaultIds, async (...efses) => {
  efses[0].writeFile('content1');
  efses[1].writeFile('content2');
  efses[2].writeFile('content3');
}); 
```

This will automatically release the locks of each vault and still allows us to retain the `with` pattern we have grown to use and love.

The only issue is, instead of allowing to directly stream the vault names in, we would need to compile them up and send them separately so we can acquire all the relevant locks in advance. This makes the implementation much simpler. The dynamic implementation can be tackled when I have more in-depth understanding of the Polykey architecture.

Did I miss anything @tegefaulkes?

**Comment by CMCDragonkai** [comment]
Well if you're using js-resources pattern, they are built compositionally, so it's all related to each other. The acquire ones are the procedural primitives, then composed together to present the bracketing pattern.

Similarly - over the RPC - bracketing abstraction can occur within a stream life-time, but for long-running transactions, it would need a more procedural thing with a state maintained via a cache state instead (similar to shopping carts).

In both cases, OCC is the preferred resolution system for most operations, PCC is specific to global operations that require unblocked execution - that is where resource starvation is unacceptable. We don't really have that many of these situations that I think of.

**Comment by aryanjassal** [comment]
Our initial plan was to utilise the `metadata` in all RPC handlers to initially send the vault names, but I'm not too happy with this approach. An alternative approach is to use a combined type like `VaultsListMessage | ContentMessage`, and the first message could be populating the vaults list, and all subsequent messages could be operating on the listed messages.

This approach of switching contexts has also been used in `secrets env` command to switch between secret path parsing and command parsing. This will take more effort to implement, but is more elegant and robust than putting the list in the metadata.

Something similar can be done for other RPC methods which rely on the metadata to transmit behavioural flags, like `VaultsSecretsRemove`. It is a duplex stream, which takes in a stream of secret paths. Each path cannot have recursive set, as we would have conflicts for recursive priority. Instead, the first message could set up the state of the system by passing in all relevant flags, then subsequent calls can write the actual data instead.

What do you think, @tegefaulkes?

**Comment by tegefaulkes** [comment]
Yeah, it's workable. You just need to make sure that the conditions witch one message is used vs the other are clear. So in this case we want to include some data at the beginning so its acting like a header message. They needs to be conveyed nicely on the caller side.

**Comment by aryanjassal** [comment]
Should I make a new handler for this like `writeM` and `readM` (for read/write multiple), or do I modify the existing `writeF` and `readF` (and `writeG` and `readG`)? Because modifying the existing functions will mean a pretty large-scale refactoring as a lot of things use this, both in Polykey and Polykey CLI. On the other hand, we will get consistency with `VaultManager.withVaults`.

It was our initial plan to replace `read*`/`write*` and instead of allowing a single vault, ask for an array of them, but is it a good idea to do this?

**Comment by tegefaulkes** [comment]
Its fine to refactor the existing one. The only change is that anything calling it needs to use an array when selecting the vault. Its a pretty minor change.

**Comment by aryanjassal** [comment]
> Its fine to refactor the existing one. The only change is that anything calling it needs to use an array when selecting the vault. Its a pretty minor change.

This wouldn't quite work, as currently, we call the `readF` and `writeF` via `vault.readF`, and it doesn't make sense to provide a list of vaults to a method of the `Vault` class.

Instead, a resource acquire pattern will be used. The exact details will depend on the implementation, but this will be the general direction.

```
// Acquire resources
const [release1, efs1] = vault1.acquireWrite();
const [release2, efs2] = vault2.acquireWrite();

// Do stuff with efs
// ...

// Release the resource (Important!!!)
release1();
release2();
```

**Comment by aryanjassal** [comment]
Marking this issue as blocking `secrets cp` and `secrets mv` as we would need the transaction open continuously for all secret paths.

**Comment by CMCDragonkai** [comment]
Demonstrate this on next cycle meeting.
